### ISSUE TITLE
leetmouse-gui does not work 

### ISSUE THREAD

**Issue by Celibistrial** [systemofapwne/leetmouse#12]
❯ sudo python3 main.py
```
Traceback (most recent call last):
  File "/home/celibistrial/leetmouse-gui/main.py", line 12, in <module>
    "Midpoint": ModuleParameter("Midpoint")
  File "/home/celibistrial/leetmouse-gui/ModuleParameter.py", line 7, in __init__
    f = open("/sys/module/leetmouse/parameters/" + self.parameterName, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/module/leetmouse/parameters/Midpoint'
```

**Comment by Cloudperry** [comment]
It doesn't work with this version of leetmouse as stated in the commits of that project. The latest version only works with Skyl3r/leetmouse (which doesn't even build for me). 

Look for the commit "Compatibility change for Systemofapwne/LEETMOUSE." and download that version of leetmouse-gui.

**Comment by Celibistrial** [comment]
Thanks, it works now

**Comment by jaredcrean** [comment]
@Cloudperry try switching to the testing branch. I had to switch to the test branch for it to build on my arch system.

**Comment by samuk10** [comment]
i managet to make it to work for this project also: 
https://github.com/Skyl3r/leetmouse-gui/pull/4
