### ISSUE TITLE
echo: I/O error in leetmouse_manage unbind_all on Ubuntu 22.04

### ISSUE THREAD

**Issue by laurirasanen** [systemofapwne/leetmouse#16]
Attempting to unbind throws error at `echo -ne "1" > /sys/module/leetmouse/parameters/no_bind`:

```
$ sudo /usr/lib/udev/leetmouse_manage unbind_all
/usr/lib/udev/leetmouse_manage: 25: echo: echo: I/O error
```

system: Ubuntu 22.04 LTS
```
$ uname -a
Linux hal 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

The script works as expected with `#!/bin/bash` rather than `#!/bin/sh`, since Ubuntu maps sh to dash by default.

```$ file -h /bin/sh
$ file -h /bin/sh
/bin/sh: symbolic link to dash
$ file -h /bin/bash
/bin/bash: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=33a5554034feb2af38e8c75872058883b2988bc5, for GNU/Linux 3.2.0, stripped

```

**Comment by systemofapwne** [comment]
Thanks. I will rewrite the scripts to explicitely use bash then.

**Comment by Thatrius** [comment]
Is there a fix for this yet? I can't seem to unbind either, getting the same error.

**Comment by systemofapwne** [comment]
The script now explicitly uses bash. Please give this a try and report back, if it works.
