### ISSUE TITLE
How do I turn it off? (please help!)

### ISSUE THREAD

**Issue by Thatrius** [systemofapwne/leetmouse#22]
So I installed Leetmouse today on Ubuntu; but now I can't seem to change any of the settings, or even turn it off. `/driver/config.h` was mentioned in the description, but I can't find it anywhere. There _is_ a config.sample.h, but modifying it doesn't appear to affect anything.

And of course, trying to run 
`sudo /usr/lib/udev/leetmouse_manage unbind_all `
simply results in
`/usr/lib/udev/leetmouse_manage: 25: echo: echo: I/O error`.

I also tried uninstalling _without_ unbinding first, but the mouse never reverted back. Now I'm not sure what to do. Is there any way I can either change the settings, or restore my mouse to how it was originally? 

thanks!

**Comment by systemofapwne** [comment]
The config.h parameters only have an affect before compiling it.

Changing the parameters during runtime can be done via the kernelmodules parameters, that are exposed in the device tree at /sys/module/leetmouse/parameters/
