### ISSUE TITLE
Graphical tablets don't work with leetmouse

### ISSUE THREAD

**Issue by fluentpwn** [systemofapwne/leetmouse#26]
Using graphical tablets with leetmouse installed causes them not to be properly recognized by libinput or wacom driver - look at https://gitlab.freedesktop.org/libinput/libinput/-/issues/843. 

According to udev, it's usb driver is assigned to leetmouse, and that causes both udev and libinput not to recognize the device properly(udev recognizes tablet as mouse tablet, libinput says it's missing every needed property).

**Comment by systemofapwne** [comment]
Sorry for the late reply. Since i have no such tablet, i cannot test this. My naive idea would be to exclude these tablets in the udev rule. But for that, i need more information. Especially how that tablet describes itself to the USB bus. Please hand in a verbose lsusb -v report on that device.

**Comment by fluentpwn** [comment]
Hoi! I just ended up not doing an udev_install but rather making a custom udev rule that only binds my mouse to the driver.

This is my udev rule:
`ATTRS{product}=="G203 LIGHTSYNC Gaming Mouse", RUN+="/usr/lib/udev/leetmouse_bind leetmouse $id:1.0"`
Just replace the product string with your mouse and 1.0 with what's matching there(I don't remember how I got it lol).

[lsusb -v for the device](https://github.com/systemofapwne/leetmouse/files/11313680/graphtablet.txt)
