### ISSUE TITLE
Bad return status for module build on kernel: 6.2.8-arch1-1

### ISSUE THREAD

**Issue by Thomot512** [systemofapwne/leetmouse#30]
When I updated to the latest kernel on Arch Linux I got the following error:
```
dkms install --no-depmod leetmouse-driver/0.9.0 -k 6.2.8-arch1-1
Error! Bad return status for module build on kernel: 6.2.8-arch1-1 (x86_64)
Consult /var/lib/dkms/leetmouse-driver/0.9.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod leetmouse-driver/0.9.0 -k 6.2.8-arch1-1' exited 10
```

[make.log](https://github.com/systemofapwne/leetmouse/files/11071740/make.log)

The driver is therefor not working anymore.

**Comment by Thomot512** [comment]
Found out what went wrong.
I followed the ReadMe and created a config.h file with my own config in it.
If instead of doing that I modify the config.sample.h, works like a charm.

**Comment by DontStarve72** [comment]
Bizarrely this worked for me too

**Comment by systemofapwne** [comment]
I just ran into the same problem after upgrading to 6.1.21-1. Possibly some internal changes in DKMS. I will investigate this trivial issue and push a quick-fix soon.

**Comment by systemofapwne** [comment]
Fixed in latest release.
