### ISSUE TITLE
Installing stops graphics tablet drivers from working

### ISSUE THREAD

**Issue by nishiiko** [systemofapwne/leetmouse#34]
Each time I install the driver, the accel is applied appropriately but the driver I use for my tablet, opentabletdriver, stops detecting my tablet

**Comment by systemofapwne** [comment]
https://github.com/systemofapwne/leetmouse/blob/master/install_files/udev/99-leetmouse.rules

**Comment by systemofapwne** [comment]
You need to add an exclusion to the udev rules for your specific device, so that leetmouse does not blind to it: https://github.com/systemofapwne/leetmouse/blob/master/install_files/udev/99-leetmouse.rules

**Comment by nishiiko** [comment]
Understood, thanks!

**Comment by systemofapwne** [comment]
For anyone, who is interested in the solution: Here I answer a bit more in detail: https://reddit.com/r/MouseAccel/s/i4TuMJOn9L
