### ISSUE TITLE
[Support] X-Y axis sensitivity ratio

### ISSUE THREAD

**Issue by nishiiko** [systemofapwne/leetmouse#38]
Could you add a setting to change the ratio between X and Y sensitivity? i.e. having 1.35 ratio will make Y axis sensitivity 1.35 higher than X axis sensitivity.

**Comment by Thomot512** [comment]
#define POST_SCALE_X 1.0f
#define POST_SCALE_Y 1.35f

Should do the trick.

**Comment by systemofapwne** [comment]
> #define POST_SCALE_X 1.0f #define POST_SCALE_Y 1.35f
> 
> Should do the trick.

Similarily, PRE_SCALE_X and PRE_SCALE_Y exist.
