### ISSUE TITLE
Doesn't work with Secure Boot

### ISSUE THREAD

**Issue by baanan** [systemofapwne/leetmouse#42]
For some reason, the driver has stopped working for me since this morning. I was using the fixed-point version in #28, but even when switching to the master branch it still doesn't work. The interesting thing, though, is that it would complain that the module wasn't loaded when uninstalling. When poking around various things for modules:

<ul>
  <li><code>lsmod | grep leetmouse</code> shows nothing.</li>
  <li><code>modinfo leetmouse</code> does show a list of info:
<details>
  <summary>modinfo</summary>
  <pre><code>filename:       /lib/modules/6.5.6-76060506-generic/kernel/drivers/hid/leetmouse.ko.zst
license:        GPL
description:    USB HID mouse driver with acceleration (LEETMOUSE)
author:         Vojtech Pavlik <vojtech@ucw.cz>
author:         Klaus Zipfel <klaus (at) zipfel (dot) family>
author:         Christopher Williams <chilliams (at) gmail (dot) com>
srcversion:     B4C602065B4B63174DE58C6
alias:          usb:v*p*d*dc*dsc*dp*ic03isc01ip02in*
depends:        
retpoline:      Y
name:           leetmouse
vermagic:       6.5.6-76060506-generic SMP preempt mod_unload modversions 
parm:           debug:byte
parm:           no_bind:This will disable binding to this driver via 'leetmouse_bind' by udev. (byte)
parm:           update:Triggers an update of the acceleration parameters below (byte)
parm:           PreScaleX:Prescale X-Axis before applying acceleration. (charp)
parm:           PreScaleY:Prescale Y-Axis before applying acceleration. (charp)
parm:           SpeedCap:Limit the maximum pointer speed before applying acceleration. (charp)
parm:           Sensitivity:Mouse base sensitivity. (charp)
parm:           Acceleration:Mouse acceleration sensitivity. (charp)
parm:           SensitivityCap:Cap maximum sensitivity. (charp)
parm:           Offset:Mouse base sensitivity. (charp)
parm:           PostScaleX:Postscale X-Axis after applying acceleration. (charp)
parm:           PostScaleY:Postscale >-Axis after applying acceleration. (charp)
parm:           ScrollsPerTick:Amount of lines to scroll per scroll-wheel tick. (charp)</code></pre>
</details></li>
  <li><code>sudo modprobe leetmouse</code> outputs <code>modprobe: ERROR: could not insert 'leetmouse': Key was rejected by service</code></li>
</ul>

Some other info:
- os: `Pop!_OS 22.04 LTS x86_64`
- kernel version: `6.5.6-76060506-generic`
- I've enabled secure boot using [this guide](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#PreLoader) (by adapting it for Pop) in order to dual-boot with Windows
  - This seems to be something that comes up when searching up the modprobe error
  - But it worked for a long time (around a month and through multiple kernel changes) before breaking

**Comment by baanan** [comment]
I can confirm that disabling secure boot fixes it, but I'd like to be able to re-enable it

**Comment by systemofapwne** [comment]
The module needs either to get signed by a key trusted by your SB infrastructure or checks for kernel module signing must be disabled. 
I am using Secure Boot my own with no problems so far. I have my own SB keys enrolled and dkms seems to sign my module properly, how I can see via modinfo:

``
# modinfo leetmouse
filename:       /lib/modules/6.5.11-1-MANJARO/updates/dkms/leetmouse.ko.zst
               ......
name:           leetmouse
vermagic:       6.5.11-1-MANJARO SMP preempt mod_unload 
sig_id:         PKCS#7
signer:         DKMS module signing key
sig_key:        0D:0E:C9:08:B2:BA:3E:DF:FA:CE:84:8F:C5:33:E2:2E:AB:DA:FF:5C
sig_hashalgo:   sha512
signature:      80:AC:B3:5F:00:9F:DD:55:68:74:1A:6A:E4:28:7C:D6:C0:81:40:9F:
                DA:32:E4:98:F8:1E:BD:E3:39:2D:D1:4A:03:4E:00:5A:57:C4:3B:0B:
                D8:19:A4:A9:B7:E4:8D:3D:74:89:50:DD:1F:D3:86:2B:2F:70:07:0B:
                23:78:1A:C2:49:4D:2F:63:8C:30:D9:50:14:09:8E:49:0F:F3:D2:BE:
                02:63:26:28:79:D9:42:BB:AF:52:67:FA:BA:EA:D9:21:26:E1:B2:58:
                8D:1B:F0:A6:7F:0F:EA:68:5A:9A:DC:61:3E:8E:39:F2:1B:BB:CB:F1:
                ......
``

Can you please check, if your module got signed? Do you have any other out-of-tree modules in use? Especially DKMS? If yes: Are those signed?

**Comment by systemofapwne** [comment]
Closing this issue, since it is DKMS config & SecureBoot related.

**Comment by systemofapwne** [comment]
Closing this issue, since it is DKMS config & SecureBoot related.

**Comment by systemofapwne** [comment]
Closing this issue, since it is DKMS config & SecureBoot related.
