### ISSUE TITLE
Add LLVM Compiler support

### ISSUE THREAD

**Issue by ruffi123456789** [systemofapwne/leetmouse#45]
Using this on a kernel compiled with llvm seems not possible since, -mhard-float -mpreferred-stack-boundary=4 are gcc options.
Removing them just results in further errors, would love some help on this

**Comment by systemofapwne** [comment]
I highly suggest to not to run the kernel modules when compiled without these flags (can cause data corruption).
However, there are forks of this project, that completely avoid using float math in the kernel, which is way safer. Maybe give those a try: https://github.com/Cloudperry/leetmouse

**Comment by ruffi123456789** [comment]
> I highly suggest to not to run the kernel modules when compiled without these flags (can cause data corruption).

That's exactly what happened, thanks for the heads up though. Decided to bite the bullet and write my own implementation of the Quake Live mouse acceleration! Thank you very much though
